# Generated by Django 5.1.6 on 2025-03-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_practica4_bd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biblioteca',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
